[env]
TERM = "alacritty"

[window]
dimensions = { columns = 180, lines = 40 }
position = { x = 400, y = 200 }
padding = { x = 4, y = 4 }
decorations = "Buttonless"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[font]
normal = {family= "JetBrainsMono Nerd Font", style="Regular"}
size = 14

[selection]
save_to_clipboard = true


[colors]
draw_bold_text_with_bright_colors = true
cursor = { cursor = "#9EFEA4" }

[colors.primary]
background = "#010B17"
foreground = "#ADBBDA"

[colors.normal]
black =   "#20242C"
red =     "#E01A4F"
green =   "#2DE0A7"
yellow =  "#FFDF64"
blue =    "#7091E6"
magenta = "#BB9AF7"
cyan =    "#41EAD4"
white =   "#FCF7F8"

[colors.bright]
black =   "#20242C"
red =     "#FF7B8D"
green =   "#6BF0CD"
yellow =  "#FFFFB3"
blue =    "#94BFF3"
magenta = "#C6BDF6"
cyan =    "#7DF2E5"
white =   "#FFFFFF"

[cursor]
style = { shape = "Underline" }
thickness = 0.3

